apiVersion: v1
kind: Service
metadata:
  name: cassandra
  namespace: cass-operator
spec:
  type: LoadBalancer
  selector:
    cassandra.datastax.com/cluster: minikube
    cassandra.datastax.com/datacenter: dc1
  ports:
  - name: native
    port: 9042
    protocol: TCP
    targetPort: 9042